### ISSUE TITLE
MultiMC doesn't launch Minecraft

### ISSUE THREAD

**Issue by SkyTheNerd** [cobalt2727/L4T-Megascript#106]
Every time I launch Minecraft it doesn't launch because of the pre-launch script.

This is the full log https://pastebin.com/ykYL0mVQ

**Comment by theofficialgman** [comment]
Re-run the multimc install script from the megascript. This shouldn't be possible unless you lost internet connection during it. The script doesn't exist for some reason

**Comment by theofficialgman** [comment]
Oh actually you must have chosen NOT to add the mod-manager script. That's a bug, the prelaunch script should not be added to your multimc.cfg if that's your intention.

Either re-install and say YES to the mod script or open your multimc settings and remove the file under pre-launch

**Comment by SkyTheNerd** [comment]
It's fixed now but lambdacontrols doesn't do anything, do I have to use the mod-manager script to have it work?

**Comment by theofficialgman** [comment]
> It's fixed now but lambdacontrols doesn't do anything, do I have to use the mod-manager script to have it work?

Yes, the mod-manager script patches the gamecontrollerdb.txt file due to a bug in lwjgl3/glfw that misidentifies the joycons.
You can refer to the script in the megascript repo for how to do it manually if you would like. https://github.com/cobalt2727/L4T-Megascript/blob/ba64051d3d624a58b76a7354389d1ffa655404c9/assets/MultiMC/pre-launch.sh#L161-L165
